package schema

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestGenerateCreateTable(t *testing.T) {
	t.Run("basic table", func(t *testing.T) {
		tbl := Table{
			Name: "users",
			Columns: []Column{
				{Name: "id", Type: "text", IsNullable: false},
				{Name: "email", Type: "text", IsNullable: true},
			},
			PrimaryKey: &PrimaryKey{Name: "users_pkey", Columns: []string{"id"}},
		}

		ddl := generateCreateTable(tbl)
		assert.Contains(t, ddl, "CREATE TABLE users")
		assert.Contains(t, ddl, "id TEXT NOT NULL")
		assert.Contains(t, ddl, "email TEXT")
		assert.Contains(t, ddl, "CONSTRAINT users_pkey PRIMARY KEY (id)")
	})

	t.Run("table with unique and check constraints", func(t *testing.T) {
		tbl := Table{
			Name: "items",
			Columns: []Column{
				{Name: "id", Type: "text", IsNullable: false},
				{Name: "code", Type: "text", IsNullable: false},
			},
			PrimaryKey:        &PrimaryKey{Name: "items_pkey", Columns: []string{"id"}},
			UniqueConstraints: []UniqueConstraint{{Name: "items_code_key", Columns: []string{"code"}}},
			CheckConstraints:  []CheckConstraint{{Name: "items_check", Expression: "(code <> '')"}},
		}

		ddl := generateCreateTable(tbl)
		assert.Contains(t, ddl, "CONSTRAINT items_code_key UNIQUE (code)")
		assert.Contains(t, ddl, "CONSTRAINT items_check CHECK (code <> '')")
	})

	t.Run("identity column", func(t *testing.T) {
		tbl := Table{
			Name: "seq",
			Columns: []Column{
				{Name: "id", Type: "integer", IsNullable: false, IsIdentity: true, IdentityGeneration: "ALWAYS"},
			},
			PrimaryKey: &PrimaryKey{Name: "seq_pkey", Columns: []string{"id"}},
		}

		ddl := generateCreateTable(tbl)
		assert.Contains(t, ddl, "GENERATED ALWAYS AS IDENTITY")
	})

	t.Run("column with default", func(t *testing.T) {
		tbl := Table{
			Name: "t",
			Columns: []Column{
				{Name: "active", Type: "boolean", IsNullable: false, Default: "true"},
			},
		}

		ddl := generateCreateTable(tbl)
		assert.Contains(t, ddl, "DEFAULT true")
	})
}

func TestGenerateColumnDef(t *testing.T) {
	t.Run("nullable column", func(t *testing.T) {
		col := Column{Name: "email", Type: "text", IsNullable: true}
		assert.Equal(t, "email TEXT", generateColumnDef(col))
	})

	t.Run("not null column", func(t *testing.T) {
		col := Column{Name: "email", Type: "text", IsNullable: false}
		assert.Equal(t, "email TEXT NOT NULL", generateColumnDef(col))
	})

	t.Run("column with default", func(t *testing.T) {
		col := Column{Name: "active", Type: "boolean", IsNullable: false, Default: "false"}
		assert.Equal(t, "active BOOLEAN NOT NULL DEFAULT false", generateColumnDef(col))
	})

	t.Run("identity column", func(t *testing.T) {
		col := Column{Name: "id", Type: "integer", IsNullable: false, IsIdentity: true, IdentityGeneration: "BY DEFAULT"}
		assert.Equal(t, "id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY", generateColumnDef(col))
	})
}

func TestGenerateCreateIndex(t *testing.T) {
	t.Run("non-unique index", func(t *testing.T) {
		idx := Index{Name: "idx_email", Columns: []string{"email"}, IsUnique: false}
		assert.Equal(t, "CREATE INDEX ASYNC idx_email ON users (email)", generateCreateIndex("users", idx))
	})

	t.Run("unique index", func(t *testing.T) {
		idx := Index{Name: "idx_code", Columns: []string{"code"}, IsUnique: true}
		assert.Equal(t, "CREATE UNIQUE INDEX ASYNC idx_code ON items (code)", generateCreateIndex("items", idx))
	})

	t.Run("multi-column index", func(t *testing.T) {
		idx := Index{Name: "idx_multi", Columns: []string{"a", "b", "c"}, IsUnique: false}
		assert.Equal(t, "CREATE INDEX ASYNC idx_multi ON t (a, b, c)", generateCreateIndex("t", idx))
	})
}

func TestGenerateDropTable(t *testing.T) {
	t.Run("drop table", func(t *testing.T) {
		assert.Equal(t, "DROP TABLE users", generateDropTable("users"))
	})
}

func TestGenerateDropIndex(t *testing.T) {
	t.Run("drop index", func(t *testing.T) {
		assert.Equal(t, "DROP INDEX idx_email", generateDropIndex("idx_email"))
	})
}

func TestGenerateAddColumn(t *testing.T) {
	t.Run("add column", func(t *testing.T) {
		col := Column{Name: "bio", Type: "text", IsNullable: true}
		assert.Equal(t, "ALTER TABLE users ADD COLUMN bio TEXT", generateAddColumn("users", col))
	})
}

func TestGenerateAddCheckConstraint(t *testing.T) {
	t.Run("add check", func(t *testing.T) {
		cc := CheckConstraint{Name: "t_check", Expression: "(x > 0)"}
		assert.Equal(t, "ALTER TABLE t ADD CONSTRAINT t_check CHECK (x > 0)", generateAddCheckConstraint("t", cc))
	})
}

func TestGenerateAddUniqueConstraint(t *testing.T) {
	t.Run("add unique", func(t *testing.T) {
		uc := UniqueConstraint{Name: "t_email_key", Columns: []string{"email"}}
		assert.Equal(t, "ALTER TABLE t ADD CONSTRAINT t_email_key UNIQUE (email)", generateAddUniqueConstraint("t", uc))
	})
}

func TestGenerateDropConstraint(t *testing.T) {
	t.Run("drop constraint", func(t *testing.T) {
		assert.Equal(t, "ALTER TABLE t DROP CONSTRAINT t_check", generateDropConstraint("t", "t_check"))
	})
}
