package schema

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParse(t *testing.T) {
	t.Run("simple schema files", func(t *testing.T) {
		f := writeTemp(t, "users.sql", `
CREATE TABLE users (
    id   TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
    name TEXT NOT NULL
);
`)
		out, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		require.NoError(t, err)
		require.Len(t, out.Schema.Tables, 1)

		tbl := out.Schema.Tables[0]
		assert.Equal(t, "users", tbl.Name)
		assert.Len(t, tbl.Columns, 2)
		assert.Equal(t, "id", tbl.Columns[0].Name)
		assert.Equal(t, "text", tbl.Columns[0].Type)
		assert.False(t, tbl.Columns[0].IsNullable)
		assert.Equal(t, "gen_random_uuid()::TEXT", tbl.Columns[0].Default)
		require.NotNil(t, tbl.PrimaryKey)
		assert.Equal(t, []string{"id"}, tbl.PrimaryKey.Columns)
	})

	t.Run("multiple tables and indexes", func(t *testing.T) {
		f := writeTemp(t, "schema.sql", `
CREATE TABLE orders (
    id     TEXT PRIMARY KEY,
    amount INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending'
);

CREATE INDEX ASYNC idx_orders_status ON orders (status);
`)
		out, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		require.NoError(t, err)
		require.Len(t, out.Schema.Tables, 1)

		tbl := out.Schema.Tables[0]
		assert.Equal(t, "orders", tbl.Name)
		require.Len(t, tbl.Indexes, 1)
		assert.Equal(t, "idx_orders_status", tbl.Indexes[0].Name)
		assert.Equal(t, []string{"status"}, tbl.Indexes[0].Columns)
		assert.False(t, tbl.Indexes[0].IsUnique)
	})

	t.Run("unique index", func(t *testing.T) {
		f := writeTemp(t, "schema.sql", `
CREATE TABLE items (
    id   TEXT PRIMARY KEY,
    code TEXT NOT NULL
);

CREATE UNIQUE INDEX ASYNC idx_items_code ON items (code);
`)
		out, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		require.NoError(t, err)
		assert.True(t, out.Schema.Tables[0].Indexes[0].IsUnique)
	})

	t.Run("table-level constraints", func(t *testing.T) {
		f := writeTemp(t, "schema.sql", `
CREATE TABLE events (
    id      TEXT NOT NULL,
    type    TEXT NOT NULL,
    payload TEXT,
    PRIMARY KEY (id),
    UNIQUE (type, id)
);
`)
		out, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		require.NoError(t, err)

		tbl := out.Schema.Tables[0]
		require.NotNil(t, tbl.PrimaryKey)
		assert.Equal(t, []string{"id"}, tbl.PrimaryKey.Columns)
		require.Len(t, tbl.UniqueConstraints, 1)
		assert.Equal(t, []string{"type", "id"}, tbl.UniqueConstraints[0].Columns)
	})

	t.Run("named constraints", func(t *testing.T) {
		f := writeTemp(t, "schema.sql", `
CREATE TABLE products (
    id    TEXT NOT NULL,
    name  TEXT NOT NULL,
    price INTEGER NOT NULL,
    CONSTRAINT products_pk PRIMARY KEY (id),
    CONSTRAINT products_name_uniq UNIQUE (name),
    CONSTRAINT products_price_positive CHECK (price > 0)
);
`)
		out, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		require.NoError(t, err)

		tbl := out.Schema.Tables[0]
		require.NotNil(t, tbl.PrimaryKey)
		assert.Equal(t, "products_pk", tbl.PrimaryKey.Name)
		require.Len(t, tbl.UniqueConstraints, 1)
		assert.Equal(t, "products_name_uniq", tbl.UniqueConstraints[0].Name)
		require.Len(t, tbl.CheckConstraints, 1)
		assert.Equal(t, "products_price_positive", tbl.CheckConstraints[0].Name)
	})

	t.Run("identity columns", func(t *testing.T) {
		f := writeTemp(t, "schema.sql", `
CREATE TABLE counters (
    id   INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    name TEXT NOT NULL,
    PRIMARY KEY (id)
);
`)
		out, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		require.NoError(t, err)

		col := out.Schema.Tables[0].Columns[0]
		assert.True(t, col.IsIdentity)
		assert.Equal(t, "ALWAYS", col.IdentityGeneration)
	})

	t.Run("by default identity", func(t *testing.T) {
		f := writeTemp(t, "schema.sql", `
CREATE TABLE seq (
    id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (id)
);
`)
		out, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		require.NoError(t, err)

		col := out.Schema.Tables[0].Columns[0]
		assert.True(t, col.IsIdentity)
		assert.Equal(t, "BY DEFAULT", col.IdentityGeneration)
	})

	t.Run("multi-word types", func(t *testing.T) {
		f := writeTemp(t, "schema.sql", `
CREATE TABLE times (
    id TEXT PRIMARY KEY,
    ts TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    dp DOUBLE PRECISION NOT NULL DEFAULT 0.0
);
`)
		out, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		require.NoError(t, err)

		cols := out.Schema.Tables[0].Columns
		assert.Equal(t, "timestamptz", cols[1].Type)
		assert.Equal(t, "double precision", cols[2].Type)
	})

	t.Run("comments are stripped", func(t *testing.T) {
		f := writeTemp(t, "schema.sql", `
-- This is a comment
CREATE TABLE t1 (
    -- This column comment should be ignored
    id TEXT PRIMARY KEY
);
`)
		out, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		require.NoError(t, err)
		assert.Len(t, out.Schema.Tables, 1)
	})

	t.Run("multiple files", func(t *testing.T) {
		f1 := writeTemp(t, "a.sql", `CREATE TABLE a (id TEXT PRIMARY KEY);`)
		f2 := writeTemp(t, "b.sql", `CREATE TABLE b (id TEXT PRIMARY KEY);`)

		out, err := Parse(context.Background(), ParseInput{Files: []string{f1, f2}})
		require.NoError(t, err)
		assert.Len(t, out.Schema.Tables, 2)
	})

	t.Run("unsupported statement returns error", func(t *testing.T) {
		f := writeTemp(t, "bad.sql", `ALTER TABLE users ADD COLUMN x TEXT;`)

		_, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		assert.Error(t, err)
		assert.Contains(t, err.Error(), "unsupported statement")
	})

	t.Run("index on unknown table returns error", func(t *testing.T) {
		f := writeTemp(t, "bad.sql", `
CREATE TABLE t1 (id TEXT PRIMARY KEY);

CREATE INDEX ASYNC idx_missing ON missing_table (id);
`)
		_, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		assert.Error(t, err)
		assert.Contains(t, err.Error(), "unknown table")
	})

	t.Run("validation error on empty input", func(t *testing.T) {
		_, err := Parse(context.Background(), ParseInput{Files: []string{}})
		assert.Error(t, err)
		assert.Contains(t, err.Error(), "invalid parse input")
	})

	t.Run("inline check constraint", func(t *testing.T) {
		f := writeTemp(t, "schema.sql", `
CREATE TABLE items (
    id     TEXT PRIMARY KEY,
    status TEXT NOT NULL CHECK (status IN ('a', 'b'))
);
`)
		out, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		require.NoError(t, err)

		tbl := out.Schema.Tables[0]
		require.Len(t, tbl.CheckConstraints, 1)
		assert.Contains(t, tbl.CheckConstraints[0].Expression, "status")
	})

	t.Run("fixture files in tests/simple", func(t *testing.T) {
		fixtureDir := filepath.Join("..", "..", "tests", "simple")
		if _, err := os.Stat(fixtureDir); os.IsNotExist(err) {
			t.Skip("fixture directory not found")
		}

		matches, err := filepath.Glob(filepath.Join(fixtureDir, "*.sql"))
		require.NoError(t, err)
		require.NotEmpty(t, matches)

		out, err := Parse(context.Background(), ParseInput{Files: matches})
		require.NoError(t, err)
		assert.Len(t, out.Schema.Tables, 3)
	})

	t.Run("column with NULL keyword", func(t *testing.T) {
		f := writeTemp(t, "schema.sql", `
CREATE TABLE t (
    id TEXT PRIMARY KEY,
    name TEXT NULL
);
`)
		out, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		require.NoError(t, err)

		col := out.Schema.Tables[0].Columns[1]
		assert.True(t, col.IsNullable)
	})

	t.Run("inline unique constraint", func(t *testing.T) {
		f := writeTemp(t, "schema.sql", `
CREATE TABLE t (
    id TEXT PRIMARY KEY,
    code TEXT NOT NULL UNIQUE
);
`)
		out, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		require.NoError(t, err)

		tbl := out.Schema.Tables[0]
		require.Len(t, tbl.UniqueConstraints, 1)
		assert.Equal(t, []string{"code"}, tbl.UniqueConstraints[0].Columns)
	})

	t.Run("table-level check constraint", func(t *testing.T) {
		f := writeTemp(t, "schema.sql", `
CREATE TABLE t (
    id TEXT PRIMARY KEY,
    val INTEGER NOT NULL,
    CHECK (val > 0)
);
`)
		out, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		require.NoError(t, err)

		tbl := out.Schema.Tables[0]
		require.Len(t, tbl.CheckConstraints, 1)
	})

	t.Run("column with varchar type", func(t *testing.T) {
		f := writeTemp(t, "schema.sql", `
CREATE TABLE t (
    id TEXT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
`)
		out, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		require.NoError(t, err)

		col := out.Schema.Tables[0].Columns[1]
		assert.Equal(t, "varchar(255)", col.Type)
	})

	t.Run("unsupported named constraint type", func(t *testing.T) {
		f := writeTemp(t, "schema.sql", `
CREATE TABLE t (
    id TEXT NOT NULL,
    CONSTRAINT t_fk FOREIGN KEY (id) REFERENCES other(id)
);
`)
		_, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		assert.Error(t, err)
		assert.Contains(t, err.Error(), "unsupported constraint type")
	})

	t.Run("empty sql file", func(t *testing.T) {
		f := writeTemp(t, "empty.sql", `-- just a comment`)

		out, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		require.NoError(t, err)
		assert.Empty(t, out.Schema.Tables)
	})

	t.Run("long unsupported statement gets truncated in error", func(t *testing.T) {
		longStmt := "INSERT INTO some_very_long_table_name_that_goes_on_and_on (col1, col2, col3, col4, col5) VALUES (1, 2, 3, 4, 5)"
		f := writeTemp(t, "bad.sql", longStmt+";")

		_, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		assert.Error(t, err)
		assert.Contains(t, err.Error(), "...")
	})

	t.Run("default with function call", func(t *testing.T) {
		f := writeTemp(t, "schema.sql", `
CREATE TABLE t (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
    ts TIMESTAMPTZ NOT NULL DEFAULT now()
);
`)
		out, err := Parse(context.Background(), ParseInput{Files: []string{f}})
		require.NoError(t, err)

		assert.Equal(t, "gen_random_uuid()::TEXT", out.Schema.Tables[0].Columns[0].Default)
		assert.Equal(t, "now()", out.Schema.Tables[0].Columns[1].Default)
	})
}

func writeTemp(t *testing.T, name, content string) string {
	t.Helper()
	dir := t.TempDir()
	p := filepath.Join(dir, name)
	err := os.WriteFile(p, []byte(content), 0644)
	require.NoError(t, err)
	return p
}
